const en = {
"{{first_name}} {{last_name}} is an adult at the start of the tournament. For adults we need following information.": "{{first_name}} {{last_name}} is an adult at the start of the tournament. For adults we need following information.",
"{{first_name}} is a minor at the start of a tournament. For minors we need following information.": "{{first_name}} is a minor at the start of a tournament. For minors we need following information.",
"A parent is present at site": "A parent is present at site",
"A photo for your badge": "A photo for your badge",
"About Bycco": "About Bycco",
"After the game the parent is picking up the player": "After the game the parent is picking up the player",
"Although optional it is recommended to provide the details of a club or league representative that is at site during the tournament": "Although optional it is recommended to provide the details of a club or league representative that is at site during the tournament",
"Back": "Back",
"Badge image": "Badge image",
"BEL rating": "BEL Rating",
"Belgian id": "Belgian id",
"Belgian rating": "Belgian rating",
"Belgian Youth Chess Championships 2020": "Belgian Youth Championships Chess 2020\n",
"Birthdate": "Birthdate",
"black": "black",
"Boys": "Boys",
"BYC 2020": "BYC 2020",
"Bycco is taking overview photos/videos of the championships and can publish these photos/videos on its website and on social media": "Bycco is taking overview photos/videos of the championships and can publish these photos/videos on its website and on social media",
"Bycco will only use this data in order to organize these championships.": "Bycco will only use this data in order to organize these championships.",
"Bycco will use all personal data like mobile numbers and email addresses for internal purposes only.": "Bycco will use all personal data like mobile numbers and email addresses for internal purposes only.",
"Calendar": "Calendar",
"Can become Belgian champion": "Can become Belgian champion",
"Category": "Category",
"Catering": "Catering",
"Chess title": "Chess title",
"Club id": "Club id",
"Confirm": "Confirm",
"Confirmation": "Confirmation",
"Confirmation details": "Confirmation details",
"Confirmation Subscription": "Confirmation Subscription",
"Contact": "Contact",
"Continue": "Continue",
"Continue reading": "Continue reading",
"Covid19 rules": "Regels Covid19",
"Date": "Date",
"Details": "Details",
"Details player": "Details player",
"Email address": "Email address",
"Email parent": "Email respresentative",
"Email player": "Email parent",
"Email representative": "Email representative",
"Enrollment": "Enrollment",
"Error": "Error",
"Federation": "Federation",
"Female": "Female",
"FIDE id": "FIDE id",
"FIDE Nationality": "FIDE Nationality",
"FIDE rating": "FIDE rating",
"Files": "Files",
"Filter categories": "Filter categories",
"First name": "first name",
"For the FIDE you are a Belgian. This means you can win the Belgian title and you can participate at the European and World Championships as part of the Belgian team.": "For the FIDE you are a Belgian. This means you can win the Belgian title and you can participate at the European and World Championships as part of the Belgian team.",
"For the FIDE you are not a Belgian. This means you cannot win the Belgian title and you cannot participate to the European and World Championships as part of the Belgian team.": "For the FIDE you are not a Belgian. This means you cannot win the Belgian title and you cannot participate to the European and World Championships as part of the Belgian team.",
"Full name": "Full name",
"Full name parent": "Full name parent",
"Full name representative": "Full name respresentative",
"Gender": "Gender",
"Girls": "Girls",
"GoalBycco": "Bycco organizes the Belgian youth championships chess as a total experience where quality comes first",
"GSM parent": "Mobile phone parent",
"GSM player": "Mobile phone player",
"GSM representative": "Mobile phone representative",
"Home": "Home",
"I agree": "I agree.",
"ID Club": "ID Club",
"ID number": "ID number",
"If Bycco is taking a close-up photos/video of a player, Bycco will explicitly ask permission to publish.": "If Bycco is taking a close-up photos/video of a player, Bycco will explicitly ask permission to publish.",
"Important information": "Important information",
"In case you do not have an id number of the RBCF, please contact your chess club, which can provide it.": "In case you do not have an id number of the RBCF, please contact your chess club, which can provide it.",
"Info about adult representative at site": "Info about adult representative at site",
"Info about parent": "Info about parent",
"Info about presence on site": "Info about presence on site",
"Internal Regulations": "Internal Regulations",
"Invalid country code": "Invalid country code",
"Invoice": "Invoice",
"Invoice details": "Invoice details",
"Invoice number": "Invoice number",
"Last name": "Last name",
"Last update on": "Last update on",
"Length badge image": "Length badge image",
"Live Games": "Live Games",
"Locale": "Locale",
"Lodging": "Lodging",
"Lodging Allocation": "Lodging Allocation",
"Lookup ID number": "Lookup ID number",
"Male": "Male",
"Mobile number": "Mobile number",
"Name": "Name",
"National id": "National id",
"National rating": "National rating",
"Nationality": "Nationality",
"Nationality FIDE": "Nationality FIDE",
"Nationality Passport": "Nationality Passport",
"New subscription": "New subscription",
"News": "News",
"News items": "News items",
"Next entry": "Next entry",
"No": "No",
"No participant with this national ID": "No participant with this national ID",
"Not a valid mobile number": "Not a valid mobile number",
"notassigned": "not assigned",
"npo.": "npo.",
"One of the required fields is invalid.": "One of the required fields is invalid.",
"Optional information": "Optional information",
"Other player": "Other player",
"Our mission": "Our mission",
"Page": "Page",
"Page not found": "Page not found",
"Pairings": "Pairings",
"Participants": "Participants",
"Pay the amount to account BE33 0017 5924 5146 of Bycco vzw. before the 25th of October with the structured message:": "Pay the amount to account BE33 0017 5924 5146 of Bycco vzw. before the 25th of October with the structured message: ",
"Payment": "Payment",
"Payment date": "Payment date",
"Payment message": "Payment message",
"Person picking up the player after the game": "Person picking up the player after the game",
"Photo": "Photo",
"Player found:": "Player found:",
"Please find attached the invoice for the subscription to the\nBelgian Youth championships 2020": "Please find attached the invoice for the subscription to the\nBelgian Youth championships 2020",
"Please provide your id number of the RBCF": "Please provide your id number of the RBCF",
"Please take into account that it takes a few days before a newly requested id number is available.": "Please take into account that it takes a few days before a newly requested id number is available.",
"Previous entry": "Previous entry",
"Price VAT excluded": "Price VAT excluded",
"Price VAT included": "Price VAT included",
"Privacy rules": "Privacy rules",
"Read more": "Read more",
"Register": "Register",
"Registration successful": "Registration successful",
"Remarks": "Remarks",
"Required information": "Required information",
"Resulting photo": "Resulting photo",
"Round": "Round",
"Rows per page": "Rijen per pagina",
"Select photo": "Select photo",
"Standings": "Standings",
"Subcription for": "Subscription for",
"SubId5": "Amount to pay",
"SubIntro2": "Your id number of the Royal Belgian Chess Federation",
"SubIntro3": "A photo for your badge",
"SubIntro5": "In case your club just requested a new id number, please take into account it can take a few days before the id number is published.",
"SubNat10": "In any case Bycco will not leak any personal information to third parties.",
"SubNat6": "Bycco will use the profile picture for a badge and for identification on the website.",
"SubPhoto1": "We need a photo to make your tournament badge. You need to select a photo by dragging a photo to the photo area or by either clicking the photo area and selecting a photo.",
"SubPhoto2": "Photo area . Drop your photo here or click to select a photo",
"SubPhoto3": "Once the photo is selected, you can move the selector handles with your mouse in order to adjust the photo. Please make sure that the face of player fills the resulting image. When the resulting image seems OK, click continue.",
"Subscribe": "Subscribe",
"Subscription": "Subscription",
"The arbiters": "The arbiters",
"The id number could not be found.": "The id number could not be found.",
"The id number is not belonging to a youth player": "The id number is not belonging to a youth player",
"The information requested below, is optional but it is highly recommended to provide it": "The information requested below, is optional but it is highly recommended to provide it",
"The organizers": "The organizers\n",
"The registration fee is 35 Euro.": "The registration fee is 35 Euro.",
"The team": "The team",
"This player is already registered": "This player is already registered",
"This player is already registered.": "This player is already registered.",
"This player is not affiliated. Please contact your club to take the necessary action.": "This player is not affiliated. Please contact your club to take the necessary action.",
"To": "To",
"To be confirmed": "To be confirmed",
"Tournament": "Tournament",
"Tournament Results": "Tournament Results",
"Tournament Rules": "Tournament Rules ",
"Tournament Subscriptions": "Tournament Subscriptions",
"UnknownError": "An unknown error occured. Please try again. If the error persists, please contact the organizers",
"Used rating": "Used rating",
"VAT": "VAT",
"VAT number": "VAT number",
"was not found.": "was not found",
"white": "white",
"Yes": "Yes",
"You are not affiliated to the FIDE. Unless you <a href=mailto:info@bycco.be>contact us</a> before the 15th of March and instruct us to explicitely do otherwise, we will affiliate you as a Belgian to the FIDE, so you can win the Belgian title and you can participate to the European and World Championships as part of the Belgian team.": "You are not affiliated to the FIDE. Unless you <a href=mailto:info@bycco.be>contact us</a> before the 15th of March and instruct us to explicitely do otherwise, we will affiliate you as a Belgian to the FIDE, so you can win the Belgian title and you can participate to the European and World Championships as part of the Belgian team.",
"You give Bycco the right to use the personal data collected in this subscription form.": "You give Bycco the right to use the personal data collected in this subscription form.",
"You need 2 items in order to subscribe to the Belgian Chess Championships:": "You need 2 items in order to subscribe to the Belgian Chess Championships:",
"You need your id number of the Royal Belgian Chess Federation in order to subscribe to the Belgian Chess Championships.": "You need your id number of the Royal Belgian Chess Federation in order to subscribe to the Belgian Chess Championships.",
"Your subscription is confirmed": "Your subscription is confirmed",
}
export default en