const fr = {
"{{first_name}} {{last_name}} is an adult at the start of the tournament. For adults we need following information.": "{{first_name}} {{last_name}} is an adult at the start of the tournament. For adults we need following information",
"{{first_name}} is a minor at the start of a tournament. For minors we need following information.": "{{first_name}} {{last_name}} est toujours un mineur au début du tournoi. Pour des mineurs on a besoin des informations suivantes.",
"A parent is present at site": "Un parent est sur place pendant le tournoi",
"A photo for your badge": "Une photo pour le badge",
"About Bycco": "Concernant Bycco",
"After the game the parent is picking up the player": "Après la partie le parent vient chercher le joueur",
"Although optional it is recommended to provide the details of a club or league representative that is at site during the tournament": "Bien que facultative",
"Back": "Retour",
"Badge image": "Photo du badge",
"BEL rating": "Elo BEL",
"Belgian id": "Matricule",
"Belgian rating": "Elo belge",
"Belgian Youth Chess Championships 2020": "Championnats de Belgique d'échecs de la jeunesse 2020",
"Birthdate": "Date de naissance",
"black": "Noirs",
"Boys": "Garçons",
"BYC 2020": "CBJ 2020",
"Bycco is taking overview photos/videos of the championships and can publish these photos/videos on its website and on social media": "Bycco prend des photos / vidéos d’ensemble lors des championnats et peut publier \n ces photos / vidéos sur le site web et sur les médias sociaux",
"Bycco will only use this data in order to organize these championships.": "Bycco n’utilisera ces données que pour l’organisation du championnat.",
"Bycco will use all personal data like mobile numbers and email addresses for internal purposes only.": "Bycco utilise les données privées (numéro GSM",
"Calendar": "Calendrier",
"Can become Belgian champion": "Peut devenir champion belge",
"Category": "Catégorie",
"Catering": "Restauration",
"Chess title": "Titre d’échecs",
"Club id": "ID cercle",
"Confirm": "Confirmer",
"Confirmation": "Confirmation",
"Confirmation details": "Détails de la confirmation",
"Confirmation Subscription": "Confirmation de l’inscription",
"Contact": "Contact",
"Continue": "Continuer",
"Continue reading": "En savoir plus",
"Covid19 rules": "Règles Covid19",
"Date": "Date",
"Details": "Détails",
"Details player": "Détails du joueur",
"Email address": "Adresse e-mail",
"Email parent": "Adresse e-mail du parent",
"Email player": "Adresse e-mail du joueur",
"Email representative": "Adresse e-mail du responsable",
"Enrollment": "Enregistrement",
"Error": "Erreur",
"Federation": "Féderation",
"Female": "Féminin",
"FIDE id": "ID FIDE",
"FIDE Nationality": "Nationalité FIDE",
"FIDE rating": "Rating FIDE",
"Files": "Fichers",
"Filter categories": "Trier par catégorie",
"First name": "Prénom",
"For the FIDE you are a Belgian. This means you can win the Belgian title and you can participate at the European and World Championships as part of the Belgian team.": "Pour la FIDE",
"For the FIDE you are not a Belgian. This means you cannot win the Belgian title and you cannot participate to the European and World Championships as part of the Belgian team.": "Pour la FIDE",
"Full name": "Nom complet",
"Full name parent": "Nom complet du parent",
"Full name representative": "Nom complet du responsable",
"Gender": "Sexe",
"Girls": "Filles",
"GoalBycco": "Bycco organise les championnats de Belgique d' échecs de la jeunesse comme une expérience totale où la qualité passe avant tout",
"GSM parent": "Numéro GSM du parent",
"GSM player": "Numéro GSM du joueur",
"GSM representative": "Numéro GSM du responsable",
"Home": "Accueil",
"I agree": "Je suis d’accord.",
"ID Club": "ID cercle",
"ID number": "Matricule",
"If Bycco is taking a close-up photos/video of a player, Bycco will explicitly ask permission to publish.": "Si Bycco prend un photo / vidéo de près d’un joueur",
"Important information": "Renseignements importants",
"In case you do not have an id number of the RBCF, please contact your chess club, which can provide it.": "Dans le cas où vous n’avez pas de matricule de la FRBE, veuillez prendre contact avec votre cercle qui fera le nécessaire",
"Info about adult representative at site": "Information sur le responsable sur place",
"Info about parent": "Information sur le parent",
"Info about presence on site": "Information sur la présence sur place",
"Internal Regulations": "Réglement Ordre Intérieur",
"Invalid country code": "Code de pays invalide",
"Invoice": "Facture",
"Invoice details": "Détails de la facture",
"Invoice number": "Numéro de facture",
"Last name": "Nom de famille",
"Last update on": "Mise à jour le",
"Length badge image": "Longeur de la photo du badge",
"Live Games": "Parties Live",
"Locale": "Langue",
"Lodging": "Séjour",
"Lodging Allocation": "Allocation Séjour",
"Lookup ID number": "Chercher matricule",
"Male": "Masculin",
"Mobile number": "Numéro mobile",
"Name": "Nom",
"National id": "Matricule",
"National rating": "Rating belge",
"Nationality": "Nationalité",
"Nationality FIDE": "Nationalité FIDE",
"Nationality Passport": "Nationalité",
"New subscription": "Nouvelle inscription",
"News": "Nouvelles",
"News items": "Des nouvelles",
"Next entry": "Message suivant",
"No": "Non",
"No participant with this national ID": "Pas de participant avec ce matricule",
"Not a valid mobile number": "Numéro de mobile invalide",
"notassigned": "non assigné",
"npo.": "asbl.",
"One of the required fields is invalid.": "Un des champs requis",
"Optional information": "Information facultative",
"Other player": "Autre joueur",
"Our mission": "Notre mission",
"Page": "Page",
"Page not found": "Page non trouvée",
"Pairings": "Appariements",
"Participants": "Participants",
"Pay the amount to account BE33 0017 5924 5146 of Bycco vzw. before the 25th of October with the structured message:": "Veuillez payer le montant au compte BE33 0017 5924 5146 de Bycco vzw. avant le 25 octobre avec le message structuré:",
"Payment": "Paiement",
"Payment date": "Date de paiement",
"Payment message": "Message de paiement",
"Person picking up the player after the game": "Personne qui vient chercher le joueur après lla partie",
"Photo": "Photo",
"Player found:": "",
"Please find attached the invoice for the subscription to the\nBelgian Youth championships 2020": "Veuillez trouver ci-joint la facture pour l'inscription au championnat de la jeunesse 2020 ",
"Please provide your id number of the RBCF": "Veuillez fournir le matricule de la FRBE.",
"Please take into account that it takes a few days before a newly requested id number is available.": "Veuillez tenir compte que ça prend quelques jours avant que le matricule\nsoit publié. ",
"Previous entry": "Message précédant",
"Price VAT excluded": "Prix TVA exclusif.",
"Price VAT included": "Prix TVA inc.",
"Privacy rules": "Confidentialité des données",
"Read more": "En savoir plus",
"Register": "S'inscrire",
"Registration successful": "Enregistrement réussi",
"Remarks": "Remarques",
"Required information": "Information requise",
"Resulting photo": "La photo résultante",
"Round": "Ronde",
"Rows per page": "Lignes per page",
"Select photo": "Selectionner Photo",
"Standings": "Classement",
"Subcription for": "Inscription pour",
"SubId5": "Montant à payer",
"SubIntro2": "Le matricule de la FRBE",
"SubIntro3": "Une photo pour le badge",
"SubIntro5": "Veuillez tenir compte il peut prendre quelques jours avant que le nouveau matricule soit publié ",
"SubNat10": "En tout cas",
"SubNat6": "Bycco utllise votre photo de profil pour le badge et pour l’identification sur le site web",
"SubPhoto1": "Nous avons besoin d’une photo pour le badge du tournoi. Vous sélectionnez une photo en faisant glisser et déposer une photo dans la zone de photo ou en cliquant sur la zone de photo.",
"SubPhoto2": "Zone de photo. Faites glisser et déposer la photo ici ou cliquez ici.",
"SubPhoto3": "Une fois la photo sélectionnée",
"Subscribe": "S'incscrire",
"Subscription": "Enregistrement",
"The arbiters": "Les arbitres",
"The id number could not be found.": "Le matricule n’est pas trouvé.",
"The id number is not belonging to a youth player": "Ce matricule n’appartient pas à un jeune.",
"The information requested below, is optional but it is highly recommended to provide it": "Les informations demandées ci-dessous sont facultatives mais il est vivement recommandé de les fournir.",
"The organizers": "Les organisateurs",
"The registration fee is 35 Euro.": "Le droit d'inscription est de 35 euros.",
"The team": "L' équipe",
"This player is already registered": "Ce joueur est déjà enregistré",
"This player is already registered.": "Ce joueur est déjà enregistré.",
"This player is not affiliated. Please contact your club to take the necessary action.": "",
"To": "A",
"To be confirmed": "A confirmer",
"Tournament": "Tournoi",
"Tournament Results": "Résultats du tournoi",
"Tournament Rules": "Règlement du Tournoi",
"Tournament Subscriptions": "Enregistrements aux championnats",
"UnknownError": "Une erreur inconnue s’est produite. Veuillez réessayer. Si l’erreur persiste",
"Used rating": "Rating utilisé",
"VAT": "TVA",
"VAT number": "Numéro de TVA",
"was not found.": "n'est pas trouvée",
"white": "Blancs",
"Yes": "Oui",
"You are not affiliated to the FIDE. Unless you <a href=mailto:info@bycco.be>contact us</a> before the 15th of March and instruct us to explicitely do otherwise, we will affiliate you as a Belgian to the FIDE, so you can win the Belgian title and you can participate to the European and World Championships as part of the Belgian team.": "Vous n’êtes pas affilié à la FIDE. Sauf si vous <a href=“mailto:info@bycco.be”>nous contactiez</a> avant le 15 mars et que vous nous instruisiez explicitement à faire autrement",
"You give Bycco the right to use the personal data collected in this subscription form.": "Vous donnez à Bycco le droit d’utiliser les données collectionnées par ce formulaire d’inscription.",
"You need 2 items in order to subscribe to the Belgian Chess Championships:": "Vous avez besoin de 2 choses pour l’enregistrement aux championnats belges",
"You need your id number of the Royal Belgian Chess Federation in order to subscribe to the Belgian Chess Championships.": "Vous avez besoin du matricule de la FRBE pour l’enregistrement aux championnats belges.",
"Your subscription is confirmed": "Votre inscription est confirmée. ",
}
export default fr