const nl = {
"A parent is present at site": "Een ouder is ter plaatse.",
"A photo for your badge": "Een foto voor je badge",
"About Bycco": "Over Bycco",
"Amount to pay": "Te betalen bedrag",
"Back": "Terug",
"Badge image": "Badgefoto",
"BEL rating": "BEL rating",
"Belgian id": "Stamnummer",
"Belgian rating": "Belgische rating",
"Belgian Youth Chess Championships 2020": "Belgisch Jeugdkampioenschappen Schaken 2020",
"Birthdate": "Geboortedatum",
"black": "zwart",
"Boys": "Jongens",
"BYC 2020": "BJK 2020",
"Calendar": "Agenda",
"Can become Belgian champion": "Kan Belgisch kampioen worden",
"Category": "Categorie",
"Catering": "Catering",
"Chess title": "Schaaktitel",
"Club id": "Club is",
"Confirm": "Bevestigen",
"Confirmation details": "Bevestigingsdetails",
"Confirmation Subscription": "Bevesting inschrijving",
"Confirmation": "Bevestiging",
"Contact": "Contact",
"Continue reading": "Lees verder",
"Continue": "Verder",
"Date": "Datum",
"Details player": "Spelerdetails",
"Details": "Details",
"Email address player": "E-mailadres speler",
"Email address": "E-mailadres",
"Email parent": "E-mail ouder",
"Email player": "E-mail speler",
"Email reprsentative": "E-mail verantwoordelijke ter plaatse",
"Error": "Fout",
"Federation": "Federation",
"Female": "Vrouwelijk",
"FIDE id": "FIDE id",
"FIDE Nationality": "FIDE Nationaliteit",
"FIDE rating": "FIDE rating",
"Files": "Bestanden",
"Filter categories": "Filter categorieën",
"First name": "Voornaam",
"Full name parent": "Volledige naam ouder",
"Full name responsible on site": "Volledige naam verantwoordelijke ter plaatse",
"Full name respresentative": "Volledige naam afgevaardigde",
"Full name": "Volledige naam",
"Gender": "Geslacht",
"Girls": "Meisjes",
"GoalBycco": "Bycco organiseert de Belgische jeugdkampioenschappen schaken als een totaalbeleving waar kwaliteit voorop staat.",
"GSM number player": "GSM nummer speler",
"GSM number representative": "GSM nummer verantwoordelijke",
"GSM number responsible on site": "GSM number verantwoordelijke ter plaatse",
"GSM number": "GSM nummer",
"GSM parent": "GSM ouder",
"GSM player": "GMS speler",
"Home": "Home",
"I agree": "Ik ben het eens.",
"ID Club": "Clubnummer",
"ID number": "Stamnummer",
"Info about adult representative at site": "Info over de afgevaardigde ter plaatse",
"Info about parent": "Info over ouder",
"Info about presence on site": "Info over aanwezigheid ter plaatse",
"Internal Regulations": "Huishoudelijk Reglement",
"Invalid country code": "Ongeldige landcode",
"Invoice details": "Factuurdetails",
"Invoice number": "Factuurnummer",
"Invoice": "Factuur",
"Last name": "Achternaam",
"Last update on": "Laatst aangepast op",
"Length badge image": "Lengte badgefoto",
"Live Games": "Live partijen",
"Locale": "Taal",
"Lodging Allocation": "Toewijzing Verblijf",
"Lodging": "Verblijf",
"Lookup ID number": "Opzoeken stamnummer",
"Male": "Mannelijk",
"Mobile number": "Mobiel nummer",
"Name": "Naam",
"National id": "Nationale ID",
"National rating": "Nationale rating",
"Nationality FIDE": "NAtionaliteit FIDE",
"Nationality Passport": "NAtionaliteit Paspoort",
"Nationality": "Nationaliteit",
"New subscription": "Nieuwe inschrijving",
"News items": "Nieuwsberichten",
"News": "Nieuws",
"Next entry": "Volgend item",
"No participant with this national ID": "Geen deelenermes met dit stamnummer",
"No": "Nee",
"Not a valid mobile number": "Ongeldig GSM-nummer",
"notassigned": "niet toegewezen",
"npo.": "vzw.",
"Optional information": "Optionele informatie",
"Other player": "Andere speler",
"Our mission": "Onze missie",
"was not found.": "kont niet gevonden worden",
"Page": "Pagina",
"Page not found": "Pagina niet gevonden",
"Pairings": "Paringen",
"Participants": "Deelnemers",
"Payment date": "Betalingsdatum",
"Payment message": "Betalingsmededeling",
"Payment": "Betaling",
"Photo": "Foto",
"Player found:": "Speler gevonden:",
"Please find attached the invoice for the subscription to the\nBelgian Youth championships 2020": "In bijlage vind je de factuur voor de inschrijving van Belgisch jeugdkamoioenschap 2020\n",
"Previous entry": "Vorig item",
"Price VAT excluded": "Prijs excl. BTW",
"Price VAT included": "Prijs incl. BTW",
"Privacy rules": "Privacyregels",
"Read more": "Lees verder",
"Register": "Inschrijven",
"Registration successful": "Registratie geslaagd",
"Remarks": "Opmerkingen",
"Required information": "Verplichte informatie",
"Resulting photo": "Resultaatfoto",
"Round": "Ronde",
"Rows per page": "Rijen per pagina",
"Select photo": "Foto kiezen",
"Standings": "Klassement",
"SubConf1": "Het inschrijvingsgeld bedraagt 35 Euro indien je je voor 1 maart 2020 inschrijft. Nadien bedraagt het 45 Euro",
"SubConf2": "Betaal het bedrag op rekening BE33 0017 5924 5146 van Bycco met de volgende gestructureerde mededeling:",
"Subcription for": "Inschrijving voor",
"SubDetail1": "{{first_name}} {{last_name}} is een volwassene bij het begin van het toernooi.\nVoor volwassenen hebben we de volgende informatie nodig.",
"SubDetail2": "Hoewel optioneel, is het aangeraden om de details te geven van een club- of ligaverantwoordelijke die tijdens het toernooi ter plaatse is.",
"SubDetail3": "{{first_name}} is nog minderjarig bij de start van het toernooi. Voor minderjarigen hebben we het volgende nodig.",
"SubDetail4": "De informatie hieronder is optioneel, maar het is aangeraden om die toch te geven.",
"SubDetail5": "Een van de verplichte velden is ongeldig",
"SubDetail6": "We hebben authenticatieproblemen vastgesteld toen er data naar de server werd gestuurd. \nWaarschijnlijk bevind je je achter een firewall die de trafiek blokkeert. Probeer de inschrijving\nopnieuw via een rechtstreeks verbinding met het Internet ",
"SubDetail7": "Een van de verplichte velden is ongeldig",
"SubId1": "Gelieve je stamnummer op te geven.",
"SubId2": "Het stamnummer werd niet gevonden.",
"SubId3": "Hou er rekening mee dat het enkele dagen duurt vooraleer een aangevraagd stamnummer beschikbaar wordt.",
"SubId4": "Dit stamnummer is niet van een jeugdspeler.",
"SubId5": "Deze speler is al geregistreerd.",
"SubIntro1": "Je hebt 2 zaken nodig om te schrijven voor het Belgisch jeugdkampioenschap",
"SubIntro2": "Je stamnummer bij de KBSB",
"SubIntro3": "Een foto voor je badge",
"SubIntro4": "In het geval dat je nog geen stamnummer van de KBSB hebt, dien je contact op te nemen met jouw club die het nodige zal doen.",
"SubIntro5": "Hou er rekening mee dat het enkele dagen duurt vooraleer een pas aangevraagd stamnummer gepubliceerd is",
"SubNat1": "Voor de FIDE ben je een Belg. Dit betekent dat je Belgisch kampioen kan worden en dat je je aan het EK / WK kan deelnemen in het Belgische team.",
"SubNat10": "In geen geval zal Bycco persoonlijke data aan derden geven",
"SubNat2": "Voor de FIDE ben je geen Belg. Dit betekent dat je geen Belgisch kampioen kan worden en dat je niet aan het EK / WK kan deelnemen in het Belgische team.",
"SubNat3": "Je hebt niet aangesloten bij de FIDE. Tenzij je <a href=‘mailto:info@bycco.be’>ons contacteert</a> voor de 15e maart en expliciet opdraagt om anders te doen, zullen we jou bij de FIDE aansluiten als Belg. Zo kan je Belgisch kampioen worden en deelnemen aan het EK / WK in het Belgische team",
"SubNat4": "Je geeft Bycco het recht om jouw persoonlijke data te gebruiken verzameld via inschrijvingsformulier. ",
"SubNat5": "Bycco zal de data enkel gebruiken binnen het kader van dit kampioenschap.",
"SubNat6": "Bycco gebruikt jouw profielfoto voor een badge en voor de identificatie op de website.",
"SubNat7": "Bycco zal al jouw persoonlijke data zoals GSM en E-mail enkel voor intern gebruik aanwenden.",
"SubNat8": "Bycco neemt overzichtsfoto's en -video's tijdens het kampioenschap en publiceert deze op de website en op sociale media.",
"SubNat9": "Indien een close-up van een speler genomen wordt, zal Bycco expliciete toestemming vragen om te publiceren.",
"SubPhoto1": "We hebben een foto nodig voor de toernooibadge. Je kiest jouw foto door ofwel een foto te slepen naar het opgegeven sleepgebied, ofwel door in het sleepgebied te klikken",
"SubPhoto2": "Sleepgebied. Sleep je foto naar hier of klik hier",
"SubPhoto3": "Eenmaal de foto gekozen, kan je de hendels met de muis verplaatsen om de foto aan te passen. Zorg ervoor dat het gezicht voldoende groot zichtbaar. Wanneer de bewerkte foto OK is, klik op verder",
"Subscribe": "Inschrijven",
"Subscription": "Inschrijving",
"The arbiters": "De scheidrechters",
"The organizers": "De organisatoren",
"The team": "Het team",
"This player is already registered": "Deze speler is reeds geregistreerd",
"To be confirmed": "Te bevestigen",
"To": "Naar",
"Tournament Results": "Toernooiresultaten",
"Tournament Rules": "Toernooireglement",
"Tournament Subscriptions": "Toernooiinschrijvingen",
"Tournament": "Toernooi",
"UnknownError": "Een onbekende fout is opgetreden. Probeer opnieuw. Indien deze fout aanhoudt, gelieve de organisatie te contacteren.",
"Used rating": "Gebruikte rating",
"VAT number": "BTW number",
"VAT": "BTW",
"white": "wit",
"Yes": "Ja",
"Your subscription is confirmed": "Jouw inschrijving is bevestigd",
}
export default nl