const nl = {
"{{first_name}} {{last_name}} is an adult at the start of the tournament. For adults we need following information.": "{{first_name}} {{last_name}} is een volwassene bij het begin van het toernooi.\nVoor volwassenen hebben we de volgende informatie nodig.",
"{{first_name}} is a minor at the start of a tournament. For minors we need following information.": "{{first_name}} is nog minderjarig bij de start van het toernooi. Voor minderjarigen hebben we het volgende nodig.",
"A parent is present at site": "Een ouder is ter plaatse.",
"A photo for your badge": "Een foto voor je badge",
"About Bycco": "Over Bycco",
"After the game the parent is picking up the player": "De ouder haalt de speler na de partij op",
"Although optional it is recommended to provide the details of a club or league representative that is at site during the tournament": "Hoewel optioneel, is het aangeraden om de details te geven van een club- of ligaverantwoordelijke die tijdens het toernooi ter plaatse is.",
"Back": "Terug",
"Badge image": "Badgefoto",
"BEL rating": "BEL rating",
"Belgian id": "Stamnummer",
"Belgian rating": "Belgische rating",
"Belgian Youth Chess Championships 2020": "Belgisch Jeugdkampioenschappen Schaken 2020",
"Birthdate": "Geboortedatum",
"black": "zwart",
"Boys": "Jongens",
"BYC 2020": "BJK 2020",
"Bycco is taking overview photos/videos of the championships and can publish these photos/videos on its website and on social media": "Bycco neemt overzichtsfoto's en -video's tijdens het kampioenschap en publiceert deze op de website en op sociale media.",
"Bycco will only use this data in order to organize these championships.": "Bycco zal de data enkel gebruiken binnen het kader van dit kampioenschap.",
"Bycco will use all personal data like mobile numbers and email addresses for internal purposes only.": "Bycco zal al jouw persoonlijke data zoals GSM en E-mail enkel voor intern gebruik aanwenden.",
"Calendar": "Agenda",
"Can become Belgian champion": "Kan Belgisch kampioen worden",
"Category": "Categorie",
"Catering": "Catering",
"Chess title": "Schaaktitel",
"Club id": "Club is",
"Confirm": "Bevestigen",
"Confirmation": "Bevestiging",
"Confirmation details": "Bevestigingsdetails",
"Confirmation Subscription": "Bevesting inschrijving",
"Contact": "Contact",
"Continue": "Verder",
"Continue reading": "Lees verder",
"Covid19 rules": "Covid19 rules",
"Date": "Datum",
"Details": "Details",
"Details player": "Spelerdetails",
"Email address": "E-mailadres",
"Email parent": "E-mail ouder",
"Email player": "E-mail speler",
"Email representative": "E-mail verantwoordelijke",
"Enrollment": "Inschrijving",
"Error": "Fout",
"Federation": "Federation",
"Female": "Vrouwelijk",
"FIDE id": "FIDE id",
"FIDE Nationality": "FIDE Nationaliteit",
"FIDE rating": "FIDE rating",
"Files": "Bestanden",
"Filter categories": "Filter categorieën",
"First name": "Voornaam",
"For the FIDE you are a Belgian. This means you can win the Belgian title and you can participate at the European and World Championships as part of the Belgian team.": "Voor de FIDE ben je een Belg. Dit betekent dat je Belgisch kampioen kan worden en dat je je aan het EK / WK kan deelnemen in het Belgische team.",
"For the FIDE you are not a Belgian. This means you cannot win the Belgian title and you cannot participate to the European and World Championships as part of the Belgian team.": "Voor de FIDE ben je geen Belg. Dit betekent dat je geen Belgisch kampioen kan worden en dat je niet aan het EK / WK kan deelnemen in het Belgische team.",
"Full name": "Volledige naam",
"Full name parent": "Volledige naam ouder",
"Full name representative": "Volledige naam verantwoordelijke",
"Gender": "Geslacht",
"Girls": "Meisjes",
"GoalBycco": "Bycco organiseert de Belgische jeugdkampioenschappen schaken als een totaalbeleving waar kwaliteit voorop staat.",
"GSM parent": "GSM ouder",
"GSM player": "GSM speler",
"GSM representative": "GSM nummer verantwoordelijke",
"Home": "Home",
"I agree": "Ik ben het eens.",
"ID Club": "Clubnummer",
"ID number": "Stamnummer",
"If Bycco is taking a close-up photos/video of a player, Bycco will explicitly ask permission to publish.": "Indien een close-up van een speler genomen wordt, zal Bycco expliciete toestemming vragen om te publiceren.",
"Important information": "Belangrijke informatie",
"In case you do not have an id number of the RBCF, please contact your chess club, which can provide it.": "In het geval dat je nog geen stamnummer van de KBSB hebt, dien je contact op te nemen met jouw club die het nodige zal doen.",
"Info about adult representative at site": "Info over de afgevaardigde ter plaatse",
"Info about parent": "Info over ouder",
"Info about presence on site": "Info over aanwezigheid ter plaatse",
"Internal Regulations": "Huishoudelijk Reglement",
"Invalid country code": "Ongeldige landcode",
"Invoice": "Factuur",
"Invoice details": "Factuurdetails",
"Invoice number": "Factuurnummer",
"Last name": "Achternaam",
"Last update on": "Laatst aangepast op",
"Length badge image": "Lengte badgefoto",
"Live Games": "Live partijen",
"Locale": "Taal",
"Lodging": "Verblijf",
"Lodging Allocation": "Toewijzing Verblijf",
"Lookup ID number": "Opzoeken stamnummer",
"Male": "Mannelijk",
"Mobile number": "Mobiel nummer",
"Name": "Naam",
"National id": "Nationale ID",
"National rating": "Nationale rating",
"Nationality": "Nationaliteit",
"Nationality FIDE": "NAtionaliteit FIDE",
"Nationality Passport": "NAtionaliteit Paspoort",
"New subscription": "Nieuwe inschrijving",
"News": "Nieuws",
"News items": "Nieuwsberichten",
"Next entry": "Volgend item",
"No": "Nee",
"No participant with this national ID": "Geen deelenermes met dit stamnummer",
"Not a valid mobile number": "Ongeldig GSM-nummer",
"notassigned": "niet toegewezen",
"npo.": "vzw.",
"One of the required fields is invalid.": "Een van de verplichte velden is ongeldig",
"Optional information": "Optionele informatie",
"Other player": "Andere speler",
"Our mission": "Onze missie",
"Page": "Pagina",
"Page not found": "Pagina niet gevonden",
"Pairings": "Paringen",
"Participants": "Deelnemers",
"Pay the amount to account BE33 0017 5924 5146 of Bycco vzw. before the 25th of October with the structured message:": "Betaal het bedrag vóór 25 oktober op rekening BE33 0017 5924 5146 van Bycco vzw. met de gestructureerde mededeling:",
"Payment": "Betaling",
"Payment date": "Betalingsdatum",
"Payment message": "Betalingsmededeling",
"Person picking up the player after the game": "Persoon die de speler ophaalt na de partij",
"Photo": "Foto",
"Player found:": "Speler gevonden:",
"Please find attached the invoice for the subscription to the\nBelgian Youth championships 2020": "In bijlage vind je de factuur voor de inschrijving van Belgisch jeugdkamoioenschap 2020\n",
"Please provide your id number of the RBCF": "Gelieve je stamnummer op te geven.",
"Please take into account that it takes a few days before a newly requested id number is available.": "Hou er rekening mee dat het enkele dagen duurt vooraleer een aangevraagd stamnummer beschikbaar wordt.",
"Previous entry": "Vorig item",
"Price VAT excluded": "Prijs excl. BTW",
"Price VAT included": "Prijs incl. BTW",
"Privacy rules": "Privacyregels",
"Read more": "Lees verder",
"Register": "Inschrijven",
"Registration successful": "Registratie geslaagd",
"Remarks": "Opmerkingen",
"Required information": "Verplichte informatie",
"Resulting photo": "Resultaatfoto",
"Round": "Ronde",
"Rows per page": "Rijen per pagina",
"Select photo": "Foto kiezen",
"Standings": "Klassement",
"Subcription for": "Inschrijving voor",
"SubId5": "Te betalen bedrag",
"SubIntro2": "Je stamnummer bij de KBSB",
"SubIntro3": "Een foto voor je badge",
"SubIntro5": "Hou er rekening mee dat het enkele dagen duurt vooraleer een pas aangevraagd stamnummer gepubliceerd is",
"SubNat10": "In geen geval zal Bycco persoonlijke data aan derden geven",
"SubNat6": "Bycco gebruikt jouw profielfoto voor een badge en voor de identificatie op de website.",
"SubPhoto1": "We hebben een foto nodig voor de toernooibadge. Je kiest jouw foto door ofwel een foto te slepen naar het opgegeven sleepgebied, ofwel door in het sleepgebied te klikken",
"SubPhoto2": "Sleepgebied. Sleep je foto naar hier of klik hier",
"SubPhoto3": "Eenmaal de foto gekozen, kan je de hendels met de muis verplaatsen om de foto aan te passen. Zorg ervoor dat het gezicht voldoende groot zichtbaar. Wanneer de bewerkte foto OK is, klik op verder",
"Subscribe": "Inschrijven",
"Subscription": "Inschrijving",
"The arbiters": "De scheidrechters",
"The id number could not be found.": "Het stamnummer werd niet gevonden.",
"The id number is not belonging to a youth player": "Dit stamnummer is niet van een jeugdspeler.",
"The information requested below, is optional but it is highly recommended to provide it": "De informatie hieronder is optioneel, maar het is aangeraden om die toch te geven.",
"The organizers": "De organisatoren",
"The registration fee is 35 Euro.": "Het inschrijvingsgeld bedraagt ​​35 euro.",
"The team": "Het team",
"This player is already registered": "Deze speler is reeds geregistreerd",
"This player is already registered.": "Deze speler is al geregistreerd.",
"This player is not affiliated. Please contact your club to take the necessary action.": "Deze speler is niet aangesloten. Neem contact op met uw club om de nodige maatregelen te nemen.",
"To": "Naar",
"To be confirmed": "Te bevestigen",
"Tournament": "Toernooi",
"Tournament Results": "Toernooiresultaten",
"Tournament Rules": "Toernooireglement",
"Tournament Subscriptions": "Toernooiinschrijvingen",
"UnknownError": "Een onbekende fout is opgetreden. Probeer opnieuw. Indien deze fout aanhoudt, gelieve de organisatie te contacteren.",
"Used rating": "Gebruikte rating",
"VAT": "BTW",
"VAT number": "BTW number",
"was not found.": "kont niet gevonden worden",
"white": "wit",
"Yes": "Ja",
"You are not affiliated to the FIDE. Unless you <a href=mailto:info@bycco.be>contact us</a> before the 15th of March and instruct us to explicitely do otherwise, we will affiliate you as a Belgian to the FIDE, so you can win the Belgian title and you can participate to the European and World Championships as part of the Belgian team.": "Je hebt niet aangesloten bij de FIDE. Tenzij je <a href=‘mailto:info@bycco.be’>ons contacteert</a> voor de 15e maart en expliciet opdraagt om anders te doen, zullen we jou bij de FIDE aansluiten als Belg. Zo kan je Belgisch kampioen worden en deelnemen aan het EK / WK in het Belgische team",
"You give Bycco the right to use the personal data collected in this subscription form.": "Je geeft Bycco het recht om jouw persoonlijke data te gebruiken verzameld via inschrijvingsformulier. ",
"You need 2 items in order to subscribe to the Belgian Chess Championships:": "Je hebt 2 zaken nodig om te schrijven voor het Belgisch jeugdkampioenschap",
"You need your id number of the Royal Belgian Chess Federation in order to subscribe to the Belgian Chess Championships.": "Je hebt je stamnummer bij de KBSB nodig om te schrijven voor het Belgisch jeugdkampioenschap.",
"Your subscription is confirmed": "Jouw inschrijving is bevestigd",
}
export default nl