// generated by server

import Vue from 'vue'
import VueI18n from 'vue-i18n'
Vue.use(VueI18n);

// api related

import openapi from '@/util/api.js'
export const api = openapi

// page related

export const available_templates = [
    "simple",
    
]


// file related

export const file_topics = [
    'Annex to page or article',
    'Report Board Meeting', 
    'Report General Assembly', 
    'Unknown',
]

// page related

export const page_doctypes = [
    'normal-page', 'article', 'app-page'
]

// role related

export const role_organisations = ['Board', 'Honour', 'Mandates']

// language related

export const locales = ['nl', 'fr', 'de', 'en']

import nl from './nl'
import fr from './fr'
import de from './de'
import en from './en'
const messages = { en, fr, nl, de };

export const i18n = new VueI18n({
  locale: 'en', 
  fallbackLocale: 'en',
  messages, 
  // silentTranslationWarn: true  
})

export function setLanguage(lang) {
  i18n.locale = lang;
}

