# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-09 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badgeimage', models.BinaryField(blank=True, verbose_name='Badge image')),
                ('badgelength', models.IntegerField(blank=True, default=0, verbose_name='Length badge image')),
                ('badgemimetype', models.CharField(blank=True, default='', max_length=20, verbose_name='Badge mimetype')),
                ('birthdate', models.DateField(null=True, verbose_name='Birthdate')),
                ('category', models.CharField(max_length=4, verbose_name='Category')),
                ('confirmed', models.BooleanField(default=False)),
                ('chesstitle', models.CharField(blank=True, max_length=4, verbose_name='Chess title')),
                ('emailparent', models.EmailField(blank=True, default='', max_length=40, verbose_name='Email parent')),
                ('emailplayer', models.EmailField(blank=True, default='', max_length=40, verbose_name='Email player')),
                ('federation', models.CharField(blank=True, max_length=4, verbose_name='Federation')),
                ('first_name', models.CharField(max_length=25, verbose_name='First name')),
                ('fullnameattendant', models.CharField(blank=True, default='', max_length=50, verbose_name='Full name responsible on site')),
                ('fullnameparent', models.CharField(blank=True, default='', max_length=50, verbose_name='Full name parent')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Gender')),
                ('idclub', models.CharField(blank=True, max_length=4, verbose_name='Club id')),
                ('idfide', models.CharField(blank=True, max_length=15, verbose_name='FIDE id')),
                ('idbel', models.CharField(max_length=6, unique=True, verbose_name='Belgian id')),
                ('locale', models.CharField(max_length=5, verbose_name='Locale')),
                ('mobileattendant', models.CharField(blank=True, default='', max_length=15, verbose_name='GSM number responsible on site')),
                ('mobileparent', models.CharField(blank=True, default='', max_length=15, verbose_name='GSM parent')),
                ('mobileplayer', models.CharField(blank=True, default='', max_length=15, verbose_name='GSM player')),
                ('last_name', models.CharField(max_length=40, verbose_name='Last name')),
                ('nationalitybel', models.CharField(blank=True, max_length=4, verbose_name='Nationality Passport')),
                ('nationalityfide', models.CharField(blank=True, max_length=4, verbose_name='Nationality FIDE')),
                ('payamount', models.IntegerField(blank=True, default=0, verbose_name='Amount to pay')),
                ('paydate', models.DateField(null=True, verbose_name='Payment date')),
                ('paymessage', models.CharField(blank=True, default='', max_length=20, verbose_name='Payment message')),
                ('rating', models.IntegerField(default=0, verbose_name='Used rating')),
                ('ratingbel', models.IntegerField(default=0, verbose_name='Belgian rating')),
                ('ratingfide', models.IntegerField(default=0, verbose_name='FIDE rating')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
                ('custom1', models.TextField(blank=True)),
                ('custom2', models.TextField(blank=True)),
                ('custom3', models.TextField(blank=True)),
            ],
        ),
    ]
