# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-09 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='chesstitle',
            field=models.CharField(blank=True, default='', max_length=4, verbose_name='Chess title'),
        ),
    ]
