# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-01 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_auto_20171209_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='present',
            field=models.DateTimeField(null=True, verbose_name='Check-in time'),
        ),
    ]
