# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-02 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_auto_20180401_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='fullnameparent',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Full name parent'),
        ),
    ]
