# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-02 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_auto_20180402_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='fullnameattendant',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Full name responsible on site'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='fullnameparent',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Full name parent'),
        ),
    ]
