# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-02 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_auto_20180402_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='CdPairing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('black', models.CharField(max_length=50)),
                ('boardnr', models.IntegerField()),
                ('result', models.CharField(max_length=6)),
                ('round', models.IntegerField()),
                ('white', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CdPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField()),
                ('chesstitle', models.CharField(blank=True, max_length=4)),
                ('clubname', models.CharField(max_length=40)),
                ('federation', models.CharField(max_length=4)),
                ('fidenation', models.CharField(blank=True, max_length=4)),
                ('fiderating', models.IntegerField(default=0)),
                ('firstname', models.CharField(max_length=25)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('id_club', models.CharField(max_length=4, verbose_name='Club id')),
                ('id_fide', models.CharField(blank=True, max_length=15, verbose_name='Fide id')),
                ('id_national', models.CharField(max_length=6, unique=True, verbose_name='National id')),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
                ('nationality', models.CharField(max_length=4, verbose_name='Nationality')),
                ('natrating', models.IntegerField(default=0, verbose_name='Fide rating')),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CdScoreCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('W', 'white'), ('B', 'black'), ('N', 'notassigned')], max_length=1)),
                ('float', models.CharField(max_length=2)),
                ('opponent', models.CharField(max_length=50)),
                ('player', models.CharField(max_length=50)),
                ('points', models.DecimalField(decimal_places=2, max_digits=4)),
                ('round', models.IntegerField()),
                ('result', models.CharField(max_length=6)),
                ('id_oppponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='subscription.CdPlayer')),
                ('id_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opponent', to='subscription.CdPlayer')),
            ],
        ),
        migrations.CreateModel(
            name='CdStanding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngames', models.IntegerField()),
                ('points', models.DecimalField(decimal_places=2, max_digits=4)),
                ('ranknr', models.IntegerField()),
                ('round', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.CdPlayer')),
            ],
        ),
        migrations.CreateModel(
            name='CdSwarJson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('round', models.IntegerField()),
                ('jsonfile', models.TextField()),
                ('uploaddate', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ACT', 'Active'), ('OUT', 'Outdated'), ('UNP', 'Unpublished')], default='UNP', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='CdTournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('shortname', models.CharField(max_length=10)),
                ('rounds', models.IntegerField(default=9)),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CdSwarTournament',
            fields=[
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='subscription.CdTournament')),
                ('swarname', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CdTournamentPrizes',
            fields=[
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='subscription.CdTournament')),
                ('jsonprizes', models.TextField(default='', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='cdplayer',
            name='id_trn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.CdTournament'),
        ),
        migrations.AddField(
            model_name='cdpairing',
            name='id_black',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='black', to='subscription.CdPlayer'),
        ),
        migrations.AddField(
            model_name='cdpairing',
            name='id_white',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='white', to='subscription.CdPlayer'),
        ),
        migrations.AddField(
            model_name='cdswarjson',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.CdSwarTournament'),
        ),
    ]
