# Generated by Django 2.1.10 on 2019-07-19 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='ByccoArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=80, verbose_name='Author')),
                ('created', models.DateTimeField(editable=False)),
                ('archived', models.DateTimeField(null=True, verbose_name='Archive date')),
                ('mainlocale', models.CharField(max_length=80, verbose_name='Main language')),
                ('maintitle', models.CharField(max_length=80, verbose_name='Title in main language')),
                ('modified', models.DateTimeField()),
                ('readmore', models.BooleanField(default=False, verbose_name='Read more shown')),
                ('published', models.DateTimeField(null=True, verbose_name='Publication date')),
                ('slug', models.CharField(max_length=80, verbose_name='Slug')),
            ],
        ),
        migrations.CreateModel(
            name='ByccoArticleLocale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(max_length=5, verbose_name='Locale')),
                ('content', models.TextField(verbose_name='Content')),
                ('intro', models.TextField(verbose_name='Intro')),
                ('title', models.CharField(max_length=80, verbose_name='Title')),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='localefields', to='byccoarticles.ByccoArticle')),
            ],
        ),
        migrations.CreateModel(
            name='ByccoArticlesIntroView',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='byccoarticles_byccoarticlesintroview', serialize=False, to='cms.CMSPlugin')),
                ('start', models.IntegerField(verbose_name='Start number article')),
                ('count', models.IntegerField(verbose_name='Number of articles')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ByccoMarkdownView',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='byccoarticles_byccomarkdownview', serialize=False, to='cms.CMSPlugin')),
                ('source', models.TextField(verbose_name='Markdown source')),
                ('sanitize', models.BooleanField(default=True, verbose_name='Sanitize html')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
