# all rights reserved
# original copyright by Ruben Decrop
# modifications by Chessdevil Consulting BVBA

import simplejson as json
import os, os.path
import datetime

board_configs = [
    {
        'venue': 'grote_zaal',
        'boards': [
            {'group': 'B12', 'board': 1},
            {'group': 'B12', 'board': 2},
            {'group': 'B12', 'board': 3},
            {'group': 'B12', 'board': 4},
        ]
    },  
    {
        'venue': 'kleine_zaal',
        'boards': [
            {'group': 'G12', 'board': 1},
            {'group': 'G12', 'board': 2},
        ]
    },  
]

swar2017 = [
    ("BJK CBJ 2017 -8.json", "BG8"),
    ("BJK CBJ 2017 -10 Boys.json", "B10"),
    ("BJK CBJ 2017 -10 Girls.json", "G10"),
    ("BJK CBJ 2017 -12 Boys.json", "B12"),
    ("BJK CBJ 2017 -12 Girls.json", "G12"),
    ("BJK CBJ 2017 -14 Boys.json", "B14"),
    ("BJK CBJ 2017 -14 Girls.json", "G14"),
    ("BJK CBJ 2017 -16 Boys.json", "B16"),
    ("BJK CBJ 2017 -16 Girls.json", "G16"),
    ("BJK CBJ 2017 -18.json", "BG18"),
    ("BJK CBJ 2017 -20.json", "BG20"),
]

def load_tournaments():
    """
    Loads the json files generated by SWAR 
    Returns:
        dict -- all the parsed tournaments, indexed by group
    """
    trn = {}
    for filename, group in swar2017:
        path = os.path.join( os.getcwd(), 'data', filename)
        with open(path, 'rb') as f:
            trn[group] =  json.load(f)
    return trn

def lookup_game(trn, round, board):
    """
    lookup a game in a tournament
    Arguments:
        trn {dict} -- the tournament
        round {integer} -- round number human
        board {integer} -- board number human
    Returns:
        tuple -- (whiteplayer, blackplayer) or None
    """
    white = None
    black = None
    for player in trn['Swar']['Player']:
        for pairing in player['RoundArray']:
            if pairing['RoundNr'] == round and pairing['Tabel'] == str(board):
                if pairing['Color'] == "White":
                    white = player
                    break
                if pairing['Color'] == 'Black':
                    black = player
                    break
    return (white, black) if white and black else None

def generate_lifechess_pgns(bc, trns, round):
    """
    Generates the content of the pgn file for livechess boards for a
    single venue
    Arguments:
        bc {dict} -- a board config for the single venue
        trns {dict} -- all the tournament files indexed by group
        round {int} -- the round number as human 
    Returns:
        str -- the generated pgn for all games in venue
    """
    pgns = [] 
    for b in bc['boards']:
        trn = trns.get(b['group'])
        if not trn:
            print('could not find tournament for group', b['group'])
            pgns.append(pgn_from_game(None, b['group'], round)) 
            continue
        game = lookup_game(trn, round, b['board'])
        if not game:
            print('Could not find game', b['group'], round, 
                b['board'])
        pgns.append(pgn_from_game(game, b['group'], round)) 
    return b'\n\n'.join(pgns)

def pgn_from_game(game, group, round):
    """
    creates an empty pgn from a game
    attention is given to encoding as pgn requires latin-1
    Arguments:
        game {tuple} -- whiteplayer,blackplayer or None
        group {str} -- the category in the tournament
        round {int} -- the round number as human
    Returns:
        str -- the pgn fro a single game
    """
    if game:
        white = game[0]['Name']
        black = game[1]['Name']
    else:
        white = '?'
        black = '?'
    return b"""[Event "Belgian Youth championships 2017 %(group)b"]
[Site "Blankenberge, Belgium BEL"]
[Date "%(today)b"]
[Round "%(round)d"]
[White "%(white)b"]
[Black "%(black)b"]
[Result "*"]

*
""" % {
    b'group': group.encode('latin-1'),
    b'today': datetime.date.today().strftime("%Y.%m.%d").encode('latin-1'),
    b'round': round,
    b'white': white.encode('utf-8'),
    b'black': black.encode('utf-8')
}

def dump_pgn(pgns):
    for i, bc in enumerate(board_configs):
        with open("{0}.pgn".format(bc['venue']), 'wb') as f:
            f.write(pgns[i])

if __name__ == "__main__":
    trns = load_tournaments()
    pgns = [generate_lifechess_pgns(bc, trns, 1) for bc in board_configs]
    dump_pgn(pgns)
    print('wrote pgn files')
