# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-28 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_trninvoice_creationdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='trninvoice',
            name='modifieddate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trninvoice',
            name='creationdate',
            field=models.DateTimeField(),
        ),
    ]
