# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-28 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_auto_20181228_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trninvoice',
            name='sentdate',
            field=models.DateTimeField(null=True),
        ),
    ]
