# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-04 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_auto_20181228_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='trninvoice',
            name='locale',
            field=models.CharField(default='en', max_length=6),
        ),
    ]
