# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-06 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_trninvoice_locale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='custom2',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='custom3',
        ),
        migrations.AddField(
            model_name='subscription',
            name='meals',
            field=models.CharField(default='', max_length=15, verbose_name='Meals'),
        ),
    ]
