# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-06 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_auto_20190406_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='meals',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Meals'),
        ),
    ]
