# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-15 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_auto_20190406_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='CdSwarPairings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField()),
                ('jsonpairings', models.TextField()),
                ('swartrn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.CdSwarTournament')),
            ],
        ),
        migrations.CreateModel(
            name='CdSwarStandings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField()),
                ('jsonstandings', models.TextField()),
                ('swartrn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.CdSwarTournament')),
            ],
        ),
    ]
