# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-04 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BelPlayer',
            fields=[
                ('birthdate', models.DateField(verbose_name='Birthdate')),
                ('chesstitle', models.CharField(blank=True, max_length=4, verbose_name='Chess title')),
                ('federation', models.CharField(max_length=4, verbose_name='Federation')),
                ('first_name', models.CharField(max_length=25, verbose_name='First name')),
                ('gender', models.CharField(max_length=1, verbose_name='Gender')),
                ('id_club', models.CharField(max_length=4, verbose_name='Club id')),
                ('id_fide', models.CharField(max_length=15, verbose_name='Fide id')),
                ('id_national', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='National id')),
                ('last_name', models.CharField(max_length=40, verbose_name='Last name')),
                ('nationality', models.CharField(max_length=4, verbose_name='Nationality')),
                ('natrating', models.IntegerField(default=0, verbose_name='Fide rating')),
            ],
        ),
        migrations.CreateModel(
            name='FidePlayer',
            fields=[
                ('first_name', models.CharField(max_length=40, verbose_name='First name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('gender', models.CharField(max_length=1, verbose_name='Gender')),
                ('id_fide', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Fide id')),
                ('chesstitle', models.CharField(blank=True, max_length=4, verbose_name='Chess title')),
                ('fiderating', models.IntegerField(default=0, verbose_name='Fide rating')),
                ('fidenation', models.CharField(max_length=4, verbose_name='Fide nation')),
            ],
        ),
    ]
