# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-04 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fideplayer',
            name='last_name',
            field=models.CharField(max_length=80, verbose_name='Last name'),
        ),
    ]
